### ISSUE TITLE
Minor installation issues

### ISSUE THREAD

**Issue by gsalzer** [tintinweb/ethereum-dasm#11]
I found some minor issues with the installation instructions.

- Running `python3 -m ethereum-dasm` to verify the installation as proposed in the README gives the error
  `No module named ethereum-dasm`
  Maybe replace the dash by an underscore?

- Running `python3 -m ethereum_dasm ...` (with whatever arguments, e.g. with `-a 0x...`) in the main directory of the git clone of the project results in an error, the last lines of the trace being

```
File "/home/user/.local/lib/python3.6/site-packages/evmdasm/instructions.py", line 141, in clone
    fork=self._fork)
TypeError: __init__() got an unexpected keyword argument 'pops'
```
This error goes away when running the command in any other directory, so it seems python finds the wrong file when started in the git directory. Documenting this behaviour would save some time.

- Running `python3 -m ethereum_dasm -a 0x....` in any directory other than the git clone (see note above) initially gives the error that the file `/home/user/.mythril/signatures.json` is missing.
The solution was to fetch this file from the mythril project (on github) and place it into the manually created directory `/home/user/.mythril`.
Again, documenting this step may help.

- I suggest to replace `python` consistently by `python3` in `README.md`. When copy&pasting the sample commands to one own's console, one gets bitten if `python` refers to version 2. (python will not find ethereum_dasm) Not a big issue, but makes the testing smoother.

**Comment by tintinweb** [comment]
Hi @gsalzer,

ad 1) yeah, thats an inconsistency that we cannos solve and I'd like to avoid renaming the project.
ad 2) did you have a previous version installed on your system? (that pops was added recently)
ad 3) filed a PR with mythril. should be published with next release https://github.com/ConsenSys/mythril/pull/545
ad 4) good point, done

thanks for your input 👍 

cheers,
tin

**Comment by tintinweb** [comment]
update ad 2) this was due to changes I introduced to the base instruction library [evmdasm](https://github.com/tintinweb/evmdasm/tree/master/evmdasm)

a `!pip install "ethereum-dasm[abidecoder,mythril]" --upgrade` should fix your problem.

cheers and thanks for reporting.

**Comment by gsalzer** [comment]
Ad 4) `README.md` now uses consistently `python3` for invoking Python. However, in most cases the space following `python3` has got lost, so the first argument or option has become part of the command.

**Comment by tintinweb** [comment]
bad QA :) thx @gsalzer
