### ISSUE TITLE
fromhex() argument must be str, not bytes

### ISSUE THREAD

**Issue by gsalzer** [tintinweb/ethereum-dasm#13]
With the command `python3 -m ethereum_dasm -a 0x1D58d303536759ADd0E9188FcEaF058Dd1157a57` the regular output is preceded by the message
```
fromhex() argument must be str, not bytes
```
Maybe an error?

**Comment by tintinweb** [comment]
Hi @gsalzer,

that was fixed in master already. I'v just published it to pypi. please upgrade `ethereum-dasm` see #11
